### ISSUE TITLE
Issue with the volume parameter (android device)

### ISSUE THREAD

**Issue by barboite** [erickzanardo/ocarina#11]
Looks like the "volume" property doesn't affect the sound output on the device (tested on virtual and physic device).
Even when set to 0, the music keeps playing:
```
  Future<OcarinaPlayer> play(Audio audio) async {
    OcarinaPlayer op = OcarinaPlayer(
        asset: DEFAULT_DIRECTORY + audio.file,
        loop: audio.loop,
        volume: 0);
    await op.load();
    await op.play;
    return op;
  }
```

Even calling `updateVolume` doesn't do the trick

**Comment by erickzanardo** [comment]
@barboite I have just tested on our example app, and volume seems to be working fine. Have you faced that on Android or iOS? Can you still reproduce this issue?

**Comment by erickzanardo** [comment]
Any news on this?

**Comment by barboite** [comment]
Hey, sorry, it was on Android. I will re-try in a few hours

**Comment by barboite** [comment]
okay, can't reproduce. Idk if i was using it wrong or if my dart/flutter upgrades did the job, but I'm closing it.

Thanks anyways :)

**Comment by erickzanardo** [comment]
Thanks for checking!
