### ISSUE TITLE
Feature request: Add 'respectSilence'

### ISSUE THREAD

**Issue by nohli** [erickzanardo/ocarina#14]
Recently (maybe with iOS 13.6), something has changed...when the phone is muted, Ocarina doesn't play any more. So users either think, the audio is broken, or complain about this change, because they would like audio during mediation, but the rest of the phone muted.
It would be really cool if there could be a variable to play audio anyway.

And thanks for this plugin, it works really well.

**Comment by nohli** [comment]
@erickzanardo I closed this, but it would still be cool.

Would it break something if AVPlayer is mixed with AVAudioSession (to get the result that it keeps playing while the phone is muted)?

**Comment by erickzanardo** [comment]
This would be cool indeed! I don't think it would break anything, I just don't think I will have time to work on this in the near future.

If you would be willing to make a pull request for this, it would be most helpful.
