### ISSUE TITLE
Updates causing issues

### ISSUE THREAD

**Issue by coffeenkeystrokes** [erickzanardo/ocarina#18]
Hi,

All was working fine yesterday until I updated flutter and android studio to latest versions. 
Issues with ocarina are now causing app to fail in run for both debug and release modes. I'm using ocarina 0.0.3 for info. 

Console is splitting out a bunch of redeclarations and then:
None of the following functions can be called with the arguments supplied: 
public constructor AssetOcarinaPlayer(url: String, volume: Double, loop: Boolean, context: Context) defined in xyz.erick.ocarina.AssetOcarinaPlayer
public constructor AssetOcarinaPlayer(url: String, volume: Double, loop: Boolean, context: Context, flutterAssets: FlutterPlugin.FlutterAssets) defined in xyz.erick.ocarina.AssetOcarinaPlayer

What went wrong:
Execution failed for task ':ocarina:compileDebugKotlin'.

I know I've been loading assets and using ocarina methods correctly as been using the package since v0.0.1 with no issues to date, until this update.

Flagging and hopefully an easy fix.

Thanks

**Comment by erickzanardo** [comment]
Please let me which version of flutter you were and which version you are now.

**Comment by coffeenkeystrokes** [comment]
Hi, 

Flutter v1.22.2
I've managed to resolve this afternoon. 
Yesterday, upgrading dependencies and flutter clean made no difference as thought it might be to do with the cache.
Spent time today removing the Ocarina plugin to check everything else worked and it did for all builds. Then added Ocarina v0.0.3 back in and is running with no problems.

Thanks

**Comment by erickzanardo** [comment]
Thanks for reporting!
