### ISSUE TITLE
[iOS] Background music is stopped

### ISSUE THREAD

**Issue by dw2kim** [erickzanardo/ocarina#21]
**Expected behaviour**
I want to play the asset audio with ocarina library without **stoping** background music (e.g. Spotify)

**Actual behaviour**
The background music is currently stoped and even does not restart after playing the audio from ocarina.

**Comment by erickzanardo** [comment]
To play things in background, you will need to use some type of background service. That is out of scope of this package, to do something like that, I suggest checking `audioplayers` which is a package with a larger feature set.
