### ISSUE TITLE
Resume after stops replays

### ISSUE THREAD

**Issue by alanmeier** [erickzanardo/ocarina#23]
Hi there,

I could not see a way to detect whether the player was actually playing or not and need a way to pause and resume sounds. In Ocarina however if you play a sound and the sound ends if you pause and resume it the resume will replay the sound when it should not as it was not playing.

So it would be nice if either resume worked as it should and not restart the sound or a way to detect if the sound is actually still playing is made available.

Thanks
Alan

**Comment by erickzanardo** [comment]
We have the `isPlaying` attribute now, as well as some listeners for it on the latest version `0.1.2`
