### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by MisterJimson** [erickzanardo/ocarina#25]
Request to update this package to use null safety.

Migration Guide: https://dart.dev/null-safety/migration-guide

Users of this package are blocked from properly migrating their codebase to be null safe until this package is migrated.

**Comment by erickzanardo** [comment]
I will get to this package eventually, but it may take a while as I have several other packages to work before.

You shouldn't be blocked to use this library even with its code not migrated yet as dart and flutter supports Unsound null safety code: https://dart.dev/null-safety/unsound-null-safety, which is basically the possibility to use an app with mixed null safe and non null safe code.

Would you be willing to submit a PR with the code migration? That would definitely speed up the time needed for me to release this with null safe

**Comment by MisterJimson** [comment]
Thanks. There is definitely a possibly one of my team members or I can PR the migration. Will let you know if we start.

**Comment by erickzanardo** [comment]
Great! Thanks

**Comment by Dave0921** [comment]
@erickzanardo I'm one of @MisterJimson's team members. I can get started on the migration PR.

**Comment by erickzanardo** [comment]
Great, looking forward to your contribution

**Comment by MisterJimson** [comment]
Available in 0.1.0 :)

**Comment by erickzanardo** [comment]
@MisterJimson and @Dave0921  Thanks for the collaboration!
