### ISSUE TITLE
No audio on physical iPhone 7

### ISSUE THREAD

**Issue by IgorKrupenja** [erickzanardo/ocarina#27]
1. Take example app code from https://github.com/erickzanardo/ocarina/tree/master/example
2. Run the project on physical iPhone 7, iOS latest (14.4).
3. Either try to play asset audio or download the file to the device and try to play it.

The sound is not playing. I am successfully able to get sound on iOS simulator, iPad Pro 2 and Android devices. I have completely reset my iPhone 7 just in case, but still no luck. I am also attaching the verbose log even though I see nothing suspicious there.

Is iPhone 7 actually supported at all? Anything else I should try to investigate this?

[ocarina.log](https://github.com/erickzanardo/ocarina/files/6223153/ocarina.log)

**Comment by erickzanardo** [comment]
There shouldn't be anything special about iPhone 7 (or any other physical device) to prevent it from working.

If it is working fine on the simulator, I suspect that there is some weird config with that particular device that is preventing the app to work?

The log indeed has nothing meaningful.

Either way, I don't have specifically an iPhone 7, but I have a 7 Plus. I will compile the example app on my device and report back to you of my findings.

**Comment by erickzanardo** [comment]
Also, which Flutter version are you using?

**Comment by erickzanardo** [comment]
Closing due inactivity, if there is more info that you can add to the issue, comment here and we can re open the issue.
