### ISSUE TITLE
isPlaying state is needed

### ISSUE THREAD

**Issue by SuTechs** [erickzanardo/ocarina#32]
Hi! there, Thank you for this plugin. I tried a lot of plugins but none of them support gapless loop. Finally tried ocarina and it worked. But I'm having a problem where I need whether the audio is playing or not. So is there any way I can get something like isPlaying?

**Comment by dw2kim** [comment]
There is open PR for this feature. #33 

cc @erickzanardo @jmacpherson

**Comment by erickzanardo** [comment]
Released on `0.1.2`
