### ISSUE TITLE
How to get a single instance of the player

### ISSUE THREAD

**Issue by alexda12** [erickzanardo/ocarina#5]
Hi Erick - I'm trying to use the plugin you have written and cannot find a way to pass a single instance of the player with an asset already loaded to any widget in my tree (via lets say Provider).

If I try and create a simple class such as : 

```
class CarinaPlayer {
 
  final OcarinaPlayer carinaPlayer;

 
  CarinaPlayer.fromCarinaPlayer(OcarinaPlayer player)
      : carinaPlayer = player:

.. etc other methods that act on carinaPlayer
}
 

```

and use like this : 

final player=    OcarinaPlayer(asset: 'my asset file', loop: true);
await player.load();
var cp=CarinaPlayer.fromCarinaPlayer(player);

... and then we pass 'cp' to any widget in our tree etc ...

When I perform the lines above the player doesnt play , there are a few errors stating the that player needs to be initialised first and there is another strange error before this ''lateinit property context has not been initialized"

I tried to run the sample and this also doesnt work for me.

**Comment by alexda12** [comment]
I just saw this issue - This appears to be what I am  seeing  : 

Doesnt work in Android #4

**Comment by erickzanardo** [comment]
@alexda12 the error it the one stated on #4? If so I will close this a duplicated

**Comment by alexda12** [comment]
@erickzanardo - The error in #4 is one part of the issue. Assuming that bug can be resolved, the plugin makes it hard to get a single instance of the plugin because you have separated constructor initialisation with loading of the asset file.

Ideally - lots of potential issues would be resolved if the constructor initialised the Player without having a need to do a : 
`
await _player.load()`

Most service based apps that would like to use this useful plugin would delegate responsibility to a  CarinaPlayer helper class that does not need to reference any specific widget and thus make this more reusable. Currently because of the **load** requirement, it makes this much harder to accomplish.

If we can do away with the **load** so that you handle this in the constructor this would be perfect.

**Comment by sallypeters** [comment]
@alexda12 I raised something similar here #3. I agree - the asynchronous load makes writing a helper class using this plugin difficult.

FYI AudioFilePlayer https://pub.dev/packages/audiofileplayer works in both iOS and Android and has looping support. Additionally, and more **importantly** it just requires constructor instantiation with no requirement for a **load** call.

iOS Looping is gapless but with Android I notice a slight pause.

With oCarina - the gapless support is much better but until the issues such as : 
- No dispose handling
- Remove need for load() etc

are resolved - I would use AudioFilePlayer

**Comment by erickzanardo** [comment]
The load method is an intentional design choice. You can't have the load be done on the constructor, as this is a call to the native platform, using the platform channel, which is an async operation, and constructors can't be async.

Also, this plugin is made to be used for one instance per sound, this too is a Design choice, I made this way from my experience on maintaining other audio plugins, like `audioplayers` and `flutter_gapless_loop`, and this decision made it much more easy to maintain this plugin.

It is no clear to me why you need to get one instance, if you explain better, I may be able to help you find a solution, but for the moment, I don't intend on changing the plugin structure for reasons I stated here.

**Comment by alexda12** [comment]
Hi Erick.
The use case I have is that I am encapsulating oCarina player in a simple reusable class which can be used throughout a flutter app.

It will have methods such as : 

```
play
pause
resume
stop
dispose

```

The actual player will be a final instance variable within this reusable class and its created via constructor instantiation : 
`
GaplessAudio({@required this.assetToPlay}) : carinaPlayer = OCarinaPlayer(asset:assetToPlay);`

And  as mentioned, this helper class will have methods like play, pause, resume etc : 
```
bool _playerLoaded=false;
  play() async {
      if (!playerLoaded){
_playerLoaded=true;
await carinaPlayer.load();
    
}
      carinaPlayer?.play();
  }

  stop() {
if (playerLoaded)
      carinaPlayer?.stop();
  }

  pause() async {
if (playerLoaded)
      carinaPlayer?.pause();
  }
```

This helper class will load the asset file once in play().

So this helper class can therefore be used in any Widget and its callback methods will successfully be called.

We can get an instance of this class like : 

 `final GaplessAudio _audio = GaplessAudio('asset');
`
and then in your widget, you can register a callback to allow you to pause/resume playing audio whenever lifecycle methods of your widget change (My requirement) : 


  ```
@override
  void initState() {
   ...
 WidgetsBinding.instance.addObserver(this);
    WidgetsBinding.instance.addPostFrameCallback((a) => _initAudio());
    super.initState();
  }

  _initAudio() async {
    await _audio.load();
  }

```
```

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      _audio.pause();
      return;
    }

    if (state == AppLifecycleState.resumed) {
      _audio.resume();
      return;
    }
  }
```


This all works perfectly for iOS.  We can simply create a helper class that just encapsulates your plugin and exposes methods to be able to  be called easily from a widget.

However - The issue is on the Android and we will receive the error : 

PlatformException(error, lateinit property context has not been initialized, null)

When your plugin is used in the context described above.

**Comment by erickzanardo** [comment]
Ok, so the only problem is that PlatformException now, since we already have an issue for that, I am gonna close this and use #4 to track this problem, I suggest you subscribe to that issue to get updates from it as I will report there my findings.
