### ISSUE TITLE
Background Notifications

### ISSUE THREAD

**Issue by vladimirlapikov** [erickzanardo/ocarina#9]
Hi, first of all :1st_place_medal: its great about solving the annoying gape in the loop, 
Can u plz add background notifications the the player with ability to control what buttons(play,pause,stop) I want to show?
Thank U :)

**Comment by erickzanardo** [comment]
Hi,

Sorry, but that kind of UI controls are not on the scope of this plugin, you should try something like this: https://pub.dev/packages/flutter_media_notification
